
-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.about_mandir (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title character varying NOT NULL DEFAULT 'About Mandir'::character varying,
  content text NOT NULL,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT about_mandir_pkey PRIMARY KEY (id)
);
CREATE TABLE public.announcements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  content text NOT NULL,
  category text,
  priority text DEFAULT 'medium'::text,
  audience text,
  visibility text DEFAULT 'Public'::text,
  is_pinned boolean DEFAULT false,
  publish_date date DEFAULT CURRENT_DATE,
  expiry_date date,
  status text DEFAULT 'active'::text,
  views integer DEFAULT 0,
  created_by text,
  notifications jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT announcements_pkey PRIMARY KEY (id)
);
CREATE TABLE public.broadcasts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  subject text NOT NULL,
  content text NOT NULL,
  channel text NOT NULL,
  status text NOT NULL,
  sent_count integer DEFAULT 0,
  total_recipients integer DEFAULT 0,
  failed_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT broadcasts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.brochures (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  temple_name text DEFAULT 'Shri Shirdi Sai Baba Mandir Chicago'::text,
  temple_subtitle text DEFAULT 'SAI SAMSTHAN USA'::text,
  temple_address text DEFAULT '1101 Foran Lane, Aurora IL 60506'::text,
  temple_phone text DEFAULT '(630) 897-1500'::text,
  temple_website text DEFAULT 'www.saisamsthanusa.org'::text,
  temple_logo_url text,
  event_title text NOT NULL,
  event_date_range text NOT NULL,
  event_image_url text,
  daily_program jsonb DEFAULT '[]'::jsonb,
  special_dates jsonb DEFAULT '[]'::jsonb,
  havan_schedule jsonb DEFAULT '[]'::jsonb,
  havan_time text DEFAULT '10:30 AM'::text,
  havan_date_range text,
  mahasamadhi_dates text,
  mahasamadhi_title text,
  footer_notes jsonb DEFAULT '[]'::jsonb,
  status text DEFAULT 'draft'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT brochures_pkey PRIMARY KEY (id)
);
CREATE TABLE public.budget_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  description text,
  budget_amount numeric DEFAULT 0,
  spent_amount numeric DEFAULT 0,
  category_type text DEFAULT 'expense'::text CHECK (category_type = ANY (ARRAY['income'::text, 'expense'::text])),
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT budget_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.budget_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  community_id uuid NOT NULL,
  budget_amount numeric NOT NULL,
  purpose text NOT NULL,
  event_name character varying,
  documents jsonb DEFAULT '[]'::jsonb,
  requested_by uuid,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying]::text[])),
  approved_by uuid,
  rejected_by uuid,
  approved_amount numeric,
  approval_notes text,
  rejection_reason text,
  reviewed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT budget_requests_pkey PRIMARY KEY (id)
);
CREATE TABLE public.budgets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  category character varying NOT NULL,
  budgeted_amount numeric NOT NULL,
  spent_amount numeric DEFAULT 0,
  period character varying DEFAULT 'monthly'::character varying CHECK (period::text = ANY (ARRAY['weekly'::character varying, 'monthly'::character varying, 'quarterly'::character varying, 'yearly'::character varying]::text[])),
  description text,
  start_date date DEFAULT CURRENT_DATE,
  end_date date,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT budgets_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cms_about (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  link_url text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cms_about_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cms_bal_vidya_mandir (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title character varying NOT NULL DEFAULT 'Bal Vidya Mandir'::character varying,
  subtitle character varying DEFAULT 'Discipline, Devotion, Development of Character'::character varying,
  quote text,
  why_bvm_title character varying DEFAULT 'Why Bala Vidya Mandir?'::character varying,
  why_bvm_content text,
  who_teaches_title character varying DEFAULT 'Who will teach?'::character varying,
  who_teaches_content text,
  who_can_join_title character varying DEFAULT 'Who can join?'::character varying,
  who_can_join_content text,
  schedule_title character varying DEFAULT 'When and where do these classes meet?'::character varying,
  schedule_items jsonb DEFAULT '[]'::jsonb,
  location text,
  syllabus_url text,
  parent_guidelines_url text,
  registration_status character varying DEFAULT 'closed'::character varying,
  registration_message text,
  registration_link text,
  contact_email character varying DEFAULT 'bvm@saisamsthanusa.org'::character varying,
  contact_phone character varying DEFAULT '(630) 897-1500'::character varying,
  class_day character varying DEFAULT 'Every Sunday'::character varying,
  class_time character varying DEFAULT '10:30 AM - 12:30 PM'::character varying,
  min_age character varying DEFAULT '5 years and above'::character varying,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cms_bal_vidya_mandir_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cms_banner (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  link_url text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  subtitile text,
  CONSTRAINT cms_banner_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cms_contact (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  email character varying NOT NULL,
  phone character varying,
  subject character varying NOT NULL,
  message text NOT NULL,
  status character varying DEFAULT 'new'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cms_contact_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cms_gallery (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title character varying,
  description text,
  image_url text NOT NULL,
  category character varying DEFAULT 'banner'::character varying,
  is_active boolean DEFAULT true,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT cms_gallery_pkey PRIMARY KEY (id),
  CONSTRAINT cms_gallery_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.cms_images (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  image_url text NOT NULL,
  title text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  description text,
  storage_path text,
  CONSTRAINT cms_images_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cms_mandir_hours (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  section_type character varying NOT NULL,
  title character varying,
  description text,
  timings jsonb DEFAULT '[]'::jsonb,
  display_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cms_mandir_hours_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cms_pujas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  slug character varying NOT NULL UNIQUE,
  description text,
  short_description character varying,
  image_url text,
  price numeric,
  price_display character varying,
  duration character varying,
  location character varying DEFAULT 'Temple Premises'::character varying,
  priest_id uuid,
  priest_name character varying,
  category character varying,
  benefits text,
  items_included text,
  booking_required boolean DEFAULT true,
  advance_booking_days integer DEFAULT 3,
  is_featured boolean DEFAULT false,
  is_active boolean DEFAULT true,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  storage_path character varying,
  CONSTRAINT cms_pujas_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cms_sai_aangan (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title character varying NOT NULL,
  description text,
  image_url text,
  timeline_updates jsonb DEFAULT '[]'::jsonb,
  donation_link text,
  display_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cms_sai_aangan_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cms_upcoming_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  event_name character varying NOT NULL,
  event_date date NOT NULL,
  day_of_week character varying,
  time_details text,
  description text,
  details_link text,
  display_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cms_upcoming_events_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cms_videos (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL UNIQUE,
  title character varying NOT NULL,
  description text,
  video_url text NOT NULL,
  thumbnail_url text,
  category character varying,
  is_featured boolean DEFAULT false,
  is_active boolean DEFAULT true,
  display_order integer DEFAULT 0,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  slug character varying UNIQUE,
  CONSTRAINT cms_videos_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cms_volunteers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  role character varying NOT NULL,
  department character varying,
  image_url text,
  description text,
  email character varying,
  phone character varying,
  social_links jsonb DEFAULT '{}'::jsonb,
  is_featured boolean DEFAULT false,
  is_active boolean DEFAULT true,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT cms_volunteers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.communication_templates (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['email'::text, 'sms'::text, 'push'::text, 'whatsapp'::text])),
  subject text,
  content text NOT NULL,
  variables jsonb DEFAULT '[]'::jsonb,
  is_active boolean DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT communication_templates_pkey PRIMARY KEY (id),
  CONSTRAINT communication_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.communities (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  slug text NOT NULL UNIQUE,
  description text,
  owner_id uuid,
  status USER-DEFINED DEFAULT 'active'::community_status,
  created_at timestamp with time zone DEFAULT now(),
  logo_url text,
  cover_image_url text,
  metadata jsonb DEFAULT '{}'::jsonb,
  settings jsonb DEFAULT '{"public_visible": true, "allow_join_requests": true}'::jsonb,
  updated_at timestamp with time zone DEFAULT now(),
  member_count integer DEFAULT 0,
  CONSTRAINT communities_pkey PRIMARY KEY (id)
);
CREATE TABLE public.community_applications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  community_id uuid NOT NULL,
  user_id uuid,
  name text NOT NULL,
  email text NOT NULL,
  phone text,
  message text NOT NULL,
  why_join text,
  skills ARRAY,
  experience text,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  review_notes text,
  applied_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT community_applications_pkey PRIMARY KEY (id),
  CONSTRAINT community_applications_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.users(id),
  CONSTRAINT community_applications_community_id_fkey FOREIGN KEY (community_id) REFERENCES public.communities(id),
  CONSTRAINT community_applications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.community_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  community_id uuid NOT NULL,
  title text NOT NULL,
  description text,
  start_date timestamp with time zone NOT NULL,
  end_date timestamp with time zone,
  location text,
  event_type text DEFAULT 'meeting'::text,
  status text DEFAULT 'published'::text,
  max_participants integer,
  current_participants integer DEFAULT 0,
  organizer_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  image_url text,
  CONSTRAINT community_events_pkey PRIMARY KEY (id),
  CONSTRAINT community_events_community_id_fkey FOREIGN KEY (community_id) REFERENCES public.communities(id)
);
CREATE TABLE public.community_members (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  community_id uuid NOT NULL,
  user_id uuid,
  role text DEFAULT 'member'::text,
  status text DEFAULT 'active'::text,
  joined_at timestamp with time zone DEFAULT now(),
  invited_by uuid,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_lead boolean DEFAULT false,
  full_name text,
  email text,
  phone text,
  CONSTRAINT community_members_pkey PRIMARY KEY (id),
  CONSTRAINT community_members_community_id_fkey FOREIGN KEY (community_id) REFERENCES public.communities(id),
  CONSTRAINT community_members_invited_by_fkey FOREIGN KEY (invited_by) REFERENCES public.users(id)
);
CREATE TABLE public.community_tasks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  community_id uuid NOT NULL,
  title text NOT NULL,
  description text,
  status text DEFAULT 'todo'::text,
  priority text DEFAULT 'medium'::text,
  assigned_to jsonb DEFAULT '[]'::jsonb,
  created_by uuid,
  due_date timestamp with time zone,
  completed_at timestamp with time zone,
  tags jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT community_tasks_pkey PRIMARY KEY (id),
  CONSTRAINT community_tasks_community_id_fkey FOREIGN KEY (community_id) REFERENCES public.communities(id)
);
CREATE TABLE public.demo_user_profiles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  full_name text NOT NULL,
  email text NOT NULL,
  phone text,
  role text NOT NULL,
  location text,
  join_date date DEFAULT CURRENT_DATE,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT demo_user_profiles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.demo_user_roles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL UNIQUE,
  display_name text NOT NULL,
  description text,
  color text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT demo_user_roles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.donation_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  description text,
  target_amount numeric DEFAULT 0,
  collected_amount numeric DEFAULT 0,
  is_active boolean DEFAULT true,
  display_order integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT donation_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.donation_receipts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  donation_id uuid NOT NULL,
  receipt_number text NOT NULL UNIQUE,
  receipt_date date DEFAULT CURRENT_DATE,
  issued_to text NOT NULL,
  issued_by text,
  receipt_template text DEFAULT 'standard'::text,
  is_digital boolean DEFAULT true,
  file_path text,
  email_sent boolean DEFAULT false,
  email_sent_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT donation_receipts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.donations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  email character varying NOT NULL,
  phone character varying,
  amount numeric NOT NULL,
  message text,
  created_at timestamp with time zone DEFAULT now(),
  payment_status text DEFAULT 'completed'::text CHECK (payment_status = ANY (ARRAY['pending'::text, 'completed'::text, 'failed'::text, 'refunded'::text])),
  donation_type text DEFAULT 'general'::text CHECK (donation_type = ANY (ARRAY['general'::text, 'puja'::text, 'annadaana'::text, 'recurring'::text, 'service'::text, 'sai_aangan'::text, 'service_to_needy'::text])),
  payment_method text DEFAULT 'cash'::text CHECK (payment_method = ANY (ARRAY['cash'::text, 'upi'::text, 'bank_transfer'::text, 'card'::text, 'cheque'::text, 'online'::text])),
  currency text DEFAULT 'INR'::text,
  donation_date date DEFAULT CURRENT_DATE,
  campaign_name character varying,
  metadata jsonb DEFAULT '{}'::jsonb,
  donor_name text,
  donor_email text,
  donor_phone text,
  purpose text,
  notes text,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT donations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.drill_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  operator_id uuid,
  start_time timestamp with time zone DEFAULT now(),
  end_time timestamp with time zone,
  sensor_data jsonb,
  alerts jsonb,
  status text DEFAULT 'active'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT drill_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT drill_sessions_operator_id_fkey FOREIGN KEY (operator_id) REFERENCES public.operators(id)
);
CREATE TABLE public.ehs_alerts (
  id bigint NOT NULL DEFAULT nextval('ehs_alerts_id_seq'::regclass),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  alert_type character varying NOT NULL,
  severity character varying NOT NULL CHECK (severity::text = ANY (ARRAY['critical'::character varying, 'high'::character varying, 'medium'::character varying, 'low'::character varying, 'info'::character varying]::text[])),
  status USER-DEFINED DEFAULT 'active'::ehs_alert_status,
  title character varying NOT NULL,
  message text NOT NULL,
  source character varying NOT NULL,
  sensor_id character varying,
  session_id uuid,
  value double precision,
  threshold double precision,
  acknowledged_at timestamp with time zone,
  acknowledged_by character varying,
  resolved_at timestamp with time zone,
  resolution_notes text,
  notification_sent boolean DEFAULT false,
  notification_channels jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT ehs_alerts_pkey PRIMARY KEY (id),
  CONSTRAINT ehs_alerts_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.ehs_drilling_sessions(id)
);
CREATE TABLE public.ehs_drill_logs (
  id bigint NOT NULL DEFAULT nextval('ehs_drill_logs_id_seq'::regclass),
  timestamp timestamp with time zone DEFAULT now(),
  rpm double precision NOT NULL,
  current_a double precision NOT NULL,
  vibration_mean double precision,
  vibration_std double precision,
  vibration_max double precision,
  depth_m double precision,
  latitude double precision,
  longitude double precision,
  predicted_material character varying,
  confidence double precision,
  category character varying,
  is_anomaly boolean DEFAULT false,
  binary_search_iterations integer,
  final_rpm integer,
  CONSTRAINT ehs_drill_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ehs_drilling_sessions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  start_time timestamp with time zone NOT NULL DEFAULT now(),
  end_time timestamp with time zone,
  hole_id character varying NOT NULL,
  grid_x double precision,
  grid_y double precision,
  collar_elevation double precision,
  target_depth_m double precision NOT NULL,
  actual_depth_m double precision,
  hole_diameter_mm double precision DEFAULT 127.0,
  total_drilling_time_s double precision,
  avg_penetration_rate double precision,
  energy_consumed_kwh double precision,
  is_active boolean DEFAULT true,
  completion_status character varying,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ehs_drilling_sessions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ehs_energy_logs (
  id bigint NOT NULL DEFAULT nextval('ehs_energy_logs_id_seq'::regclass),
  timestamp timestamp with time zone NOT NULL DEFAULT now(),
  power_kw double precision NOT NULL,
  energy_kwh double precision NOT NULL,
  voltage_v double precision,
  current_a double precision,
  power_factor double precision,
  session_id uuid,
  drilling_state character varying CHECK (drilling_state::text = ANY (ARRAY['drilling'::character varying, 'idle'::character varying, 'repositioning'::character varying]::text[])),
  is_peak_hours boolean DEFAULT false,
  cost_usd double precision,
  CONSTRAINT ehs_energy_logs_pkey PRIMARY KEY (id),
  CONSTRAINT ehs_energy_logs_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.ehs_drilling_sessions(id)
);
CREATE TABLE public.ehs_maintenance_records (
  id bigint NOT NULL DEFAULT nextval('ehs_maintenance_records_id_seq'::regclass),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  task_type character varying NOT NULL,
  component_type character varying NOT NULL,
  component_id character varying,
  scheduled_date timestamp with time zone NOT NULL,
  due_date timestamp with time zone,
  completed_date timestamp with time zone,
  status USER-DEFINED DEFAULT 'scheduled'::ehs_maintenance_status,
  priority integer DEFAULT 2 CHECK (priority >= 1 AND priority <= 3),
  description text NOT NULL,
  work_performed text,
  parts_replaced jsonb DEFAULT '[]'::jsonb,
  cost double precision,
  assigned_to character varying,
  completed_by character varying,
  triggered_by character varying,
  related_alert_id bigint,
  CONSTRAINT ehs_maintenance_records_pkey PRIMARY KEY (id),
  CONSTRAINT ehs_maintenance_records_related_alert_id_fkey FOREIGN KEY (related_alert_id) REFERENCES public.ehs_alerts(id)
);
CREATE TABLE public.ehs_material_predictions (
  id bigint NOT NULL DEFAULT nextval('ehs_material_predictions_id_seq'::regclass),
  timestamp timestamp with time zone NOT NULL DEFAULT now(),
  session_id uuid,
  depth_m double precision NOT NULL,
  predicted_material character varying NOT NULL,
  confidence double precision NOT NULL CHECK (confidence >= 0::double precision AND confidence <= 1::double precision),
  rpm double precision NOT NULL,
  current_a double precision NOT NULL,
  vibration_g double precision NOT NULL,
  pressure_bar double precision,
  temperature_c double precision,
  class_probabilities jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT ehs_material_predictions_pkey PRIMARY KEY (id),
  CONSTRAINT ehs_material_predictions_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.ehs_drilling_sessions(id)
);
CREATE TABLE public.ehs_materials (
  id integer NOT NULL DEFAULT nextval('ehs_materials_id_seq'::regclass),
  name character varying NOT NULL UNIQUE,
  hardness double precision NOT NULL,
  ucs double precision NOT NULL,
  optimal_rpm integer NOT NULL,
  density double precision NOT NULL,
  category character varying NOT NULL CHECK (category::text = ANY (ARRAY['A'::character varying, 'B'::character varying, 'C'::character varying]::text[])),
  CONSTRAINT ehs_materials_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ehs_sensor_health (
  id bigint NOT NULL DEFAULT nextval('ehs_sensor_health_id_seq'::regclass),
  timestamp timestamp with time zone NOT NULL DEFAULT now(),
  sensor_id character varying NOT NULL,
  sensor_type character varying NOT NULL,
  is_healthy boolean DEFAULT true,
  last_reading_time timestamp with time zone,
  readings_per_second double precision,
  noise_level double precision,
  drift double precision,
  out_of_range_percent double precision,
  status_message character varying,
  requires_calibration boolean DEFAULT false,
  CONSTRAINT ehs_sensor_health_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ehs_sensor_readings (
  id bigint NOT NULL DEFAULT nextval('ehs_sensor_readings_id_seq'::regclass),
  timestamp timestamp with time zone NOT NULL DEFAULT now(),
  sensor_type character varying NOT NULL CHECK (sensor_type IS NOT NULL),
  sensor_id character varying NOT NULL,
  value double precision NOT NULL,
  unit character varying NOT NULL,
  quality double precision DEFAULT 1.0 CHECK (quality >= 0::double precision AND quality <= 1::double precision),
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT ehs_sensor_readings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.email_communications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  community_id uuid,
  sender_email text NOT NULL,
  recipient_emails ARRAY NOT NULL,
  subject text NOT NULL,
  content text NOT NULL,
  template_id uuid,
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'scheduled'::text, 'sending'::text, 'sent'::text, 'failed'::text])),
  scheduled_at timestamp with time zone,
  sent_at timestamp with time zone,
  delivery_status jsonb,
  recipient_count integer DEFAULT 0,
  opened_count integer DEFAULT 0,
  clicked_count integer DEFAULT 0,
  failed_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT email_communications_pkey PRIMARY KEY (id),
  CONSTRAINT email_communications_community_id_fkey FOREIGN KEY (community_id) REFERENCES public.communities(id)
);
CREATE TABLE public.email_recipients (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email_communication_id uuid NOT NULL,
  recipient_email text NOT NULL,
  recipient_name text,
  recipient_type text DEFAULT 'user'::text CHECK (recipient_type = ANY (ARRAY['user'::text, 'volunteer'::text, 'member'::text, 'donor'::text])),
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'sent'::text, 'delivered'::text, 'opened'::text, 'clicked'::text, 'bounced'::text, 'failed'::text])),
  sent_at timestamp with time zone,
  delivered_at timestamp with time zone,
  opened_at timestamp with time zone,
  clicked_at timestamp with time zone,
  error_message text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT email_recipients_pkey PRIMARY KEY (id),
  CONSTRAINT email_recipients_email_communication_id_fkey FOREIGN KEY (email_communication_id) REFERENCES public.email_communications(id)
);
CREATE TABLE public.email_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  community_id uuid,
  name text NOT NULL,
  subject text NOT NULL,
  content text NOT NULL,
  category text DEFAULT 'general'::text CHECK (category = ANY (ARRAY['general'::text, 'announcement'::text, 'event'::text, 'volunteer'::text, 'donation'::text, 'newsletter'::text])),
  variables jsonb DEFAULT '[]'::jsonb,
  is_active boolean DEFAULT true,
  usage_count integer DEFAULT 0,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT email_templates_pkey PRIMARY KEY (id),
  CONSTRAINT email_templates_community_id_fkey FOREIGN KEY (community_id) REFERENCES public.communities(id)
);
CREATE TABLE public.event_attendees (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  event_id uuid,
  user_id uuid,
  status text DEFAULT 'registered'::text CHECK (status = ANY (ARRAY['registered'::text, 'attended'::text, 'cancelled'::text, 'no_show'::text])),
  registered_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  attended_at timestamp with time zone,
  special_requirements text,
  CONSTRAINT event_attendees_pkey PRIMARY KEY (id),
  CONSTRAINT event_attendees_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT event_attendees_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.events (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  community_id uuid,
  title text NOT NULL,
  description text,
  type text NOT NULL CHECK (type = ANY (ARRAY['festival'::text, 'meeting'::text, 'workshop'::text, 'ceremony'::text, 'volunteer_activity'::text, 'other'::text])),
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'published'::text, 'cancelled'::text, 'completed'::text])),
  starts_at timestamp with time zone NOT NULL,
  ends_at timestamp with time zone,
  timezone text DEFAULT 'Asia/Kolkata'::text,
  location jsonb,
  max_attendees integer,
  registration_required boolean DEFAULT false,
  registration_deadline timestamp with time zone,
  is_recurring boolean DEFAULT false,
  recurrence_pattern jsonb,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  image_url text,
  thumbnail_url text,
  CONSTRAINT events_pkey PRIMARY KEY (id),
  CONSTRAINT events_community_id_fkey FOREIGN KEY (community_id) REFERENCES public.communities(id),
  CONSTRAINT events_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.expense_attachments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  expense_id uuid NOT NULL,
  file_name text NOT NULL,
  file_path text NOT NULL,
  file_type text,
  file_size integer,
  uploaded_by text,
  uploaded_at timestamp with time zone DEFAULT now(),
  CONSTRAINT expense_attachments_pkey PRIMARY KEY (id),
  CONSTRAINT expense_attachments_expense_id_fkey FOREIGN KEY (expense_id) REFERENCES public.expenses(id)
);
CREATE TABLE public.expense_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  start_date date NOT NULL,
  end_date date NOT NULL,
  total_income numeric DEFAULT 0,
  total_expenses numeric DEFAULT 0,
  net_amount numeric DEFAULT 0,
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'finalized'::text, 'approved'::text])),
  created_by text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT expense_reports_pkey PRIMARY KEY (id)
);
CREATE TABLE public.expenses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  vendor_name text,
  vendor_contact text,
  vendor_address text,
  description text NOT NULL,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  currency text DEFAULT 'INR'::text,
  category text DEFAULT 'general'::text,
  subcategory text,
  expense_type text DEFAULT 'operational'::text CHECK (expense_type = ANY (ARRAY['operational'::text, 'maintenance'::text, 'utilities'::text, 'salaries'::text, 'materials'::text, 'events'::text, 'donations'::text, 'other'::text])),
  payment_method text DEFAULT 'cash'::text CHECK (payment_method = ANY (ARRAY['cash'::text, 'upi'::text, 'bank_transfer'::text, 'card'::text, 'cheque'::text, 'online'::text])),
  payment_reference text,
  payment_status text DEFAULT 'completed'::text CHECK (payment_status = ANY (ARRAY['pending'::text, 'completed'::text, 'failed'::text, 'refunded'::text])),
  expense_date date DEFAULT CURRENT_DATE,
  due_date date,
  receipt_number text,
  receipt_attached boolean DEFAULT false,
  receipt_url text,
  is_recurring boolean DEFAULT false,
  recurring_frequency text CHECK (recurring_frequency = ANY (ARRAY['weekly'::text, 'monthly'::text, 'quarterly'::text, 'yearly'::text])),
  approval_status text DEFAULT 'approved'::text CHECK (approval_status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  approved_by text,
  approved_at timestamp with time zone,
  budget_category_id uuid,
  project_id uuid,
  notes text,
  tags ARRAY,
  created_by text,
  verified_by text,
  verification_date timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT expenses_pkey PRIMARY KEY (id),
  CONSTRAINT expenses_budget_category_id_fkey FOREIGN KEY (budget_category_id) REFERENCES public.budget_categories(id)
);
CREATE TABLE public.file_uploads (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  file_name text NOT NULL,
  file_path text NOT NULL,
  file_size integer NOT NULL,
  mime_type text NOT NULL,
  uploaded_by uuid,
  community_id uuid,
  purpose text,
  is_public boolean DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT file_uploads_pkey PRIMARY KEY (id),
  CONSTRAINT file_uploads_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.users(id),
  CONSTRAINT file_uploads_community_id_fkey FOREIGN KEY (community_id) REFERENCES public.communities(id)
);
CREATE TABLE public.finance_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  type text NOT NULL CHECK (type = ANY (ARRAY['income-statement'::text, 'cash-flow'::text, 'donor-report'::text, 'custom'::text])),
  params jsonb,
  generated_by uuid,
  from_date date,
  to_date date,
  url text,
  format text,
  created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT finance_reports_pkey PRIMARY KEY (id)
);
CREATE TABLE public.health_monitoring (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  worker_id text NOT NULL,
  operator_id uuid,
  timestamp timestamp with time zone DEFAULT now(),
  vitals jsonb NOT NULL,
  face_detection jsonb,
  alerts jsonb,
  status text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT health_monitoring_pkey PRIMARY KEY (id),
  CONSTRAINT health_monitoring_operator_id_fkey FOREIGN KEY (operator_id) REFERENCES public.operators(id)
);
CREATE TABLE public.message_deliveries (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  broadcast_id uuid,
  recipient_id uuid,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'sent'::text, 'delivered'::text, 'failed'::text, 'bounced'::text])),
  provider_message_id text,
  sent_at timestamp with time zone,
  delivered_at timestamp with time zone,
  error_message text,
  retry_count integer DEFAULT 0,
  CONSTRAINT message_deliveries_pkey PRIMARY KEY (id),
  CONSTRAINT message_deliveries_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES public.users(id)
);
CREATE TABLE public.message_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  subject text,
  content text NOT NULL,
  channel text NOT NULL,
  message_type text,
  template text,
  recipient jsonb NOT NULL,
  segment text,
  delivery_status text NOT NULL,
  delivery_timestamp timestamp with time zone DEFAULT now(),
  engagement jsonb DEFAULT '{}'::jsonb,
  campaign jsonb DEFAULT '{}'::jsonb,
  sender text,
  priority text,
  failure_reason text,
  CONSTRAINT message_history_pkey PRIMARY KEY (id)
);
CREATE TABLE public.message_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  broadcast_id uuid,
  subject text,
  content text,
  channel text NOT NULL,
  recipient_name text,
  recipient_email text,
  recipient_phone text,
  delivery_status text DEFAULT 'sent'::text,
  delivery_timestamp timestamp with time zone DEFAULT now(),
  template_used text,
  error_message text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT message_logs_pkey PRIMARY KEY (id),
  CONSTRAINT message_logs_broadcast_id_fkey FOREIGN KEY (broadcast_id) REFERENCES public.broadcasts(id)
);
CREATE TABLE public.message_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  category text NOT NULL,
  description text,
  subject text,
  content text NOT NULL,
  variables jsonb DEFAULT '[]'::jsonb,
  usage integer DEFAULT 0,
  last_modified timestamp with time zone DEFAULT now(),
  created_by text,
  created_at timestamp with time zone DEFAULT now(),
  channel text DEFAULT 'email'::text CHECK (channel = ANY (ARRAY['email'::text, 'sms'::text, 'whatsapp'::text, 'push'::text])),
  CONSTRAINT message_templates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.mining_nav_alerts (
  id bigint NOT NULL DEFAULT nextval('mining_nav_alerts_id_seq'::regclass),
  session_id uuid,
  timestamp timestamp with time zone DEFAULT now(),
  alert_type text NOT NULL CHECK (alert_type = ANY (ARRAY['steep_decline'::text, 'rapid_descent'::text, 'signal_lost'::text, 'sensor_failure'::text, 'boundary_warning'::text, 'emergency'::text, 'calibration_needed'::text])),
  severity text DEFAULT 'warning'::text CHECK (severity = ANY (ARRAY['info'::text, 'warning'::text, 'critical'::text, 'emergency'::text])),
  message text NOT NULL,
  abs_x double precision,
  abs_y double precision,
  abs_z double precision,
  is_acknowledged boolean DEFAULT false,
  acknowledged_at timestamp with time zone,
  acknowledged_by text,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT mining_nav_alerts_pkey PRIMARY KEY (id),
  CONSTRAINT mining_nav_alerts_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.mining_nav_sessions(id)
);
CREATE TABLE public.mining_nav_marker_detections (
  id bigint NOT NULL DEFAULT nextval('mining_nav_marker_detections_id_seq'::regclass),
  session_id uuid,
  timestamp timestamp with time zone DEFAULT now(),
  marker_id integer NOT NULL,
  cam_x double precision,
  cam_y double precision,
  cam_z double precision,
  distance double precision,
  abs_x double precision,
  abs_y double precision,
  abs_z double precision,
  detection_confidence double precision DEFAULT 1.0,
  rvec ARRAY,
  tvec ARRAY,
  CONSTRAINT mining_nav_marker_detections_pkey PRIMARY KEY (id),
  CONSTRAINT mining_nav_marker_detections_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.mining_nav_sessions(id)
);
CREATE TABLE public.mining_nav_positions (
  id bigint NOT NULL DEFAULT nextval('mining_nav_positions_id_seq'::regclass),
  session_id uuid,
  timestamp timestamp with time zone DEFAULT now(),
  rel_x double precision DEFAULT 0,
  rel_y double precision DEFAULT 0,
  rel_z double precision DEFAULT 0,
  abs_x double precision DEFAULT 0,
  abs_y double precision DEFAULT 0,
  abs_z double precision DEFAULT 0,
  pitch double precision DEFAULT 0,
  roll double precision DEFAULT 0,
  yaw double precision DEFAULT 0,
  vel_x double precision DEFAULT 0,
  vel_y double precision DEFAULT 0,
  vel_z double precision DEFAULT 0,
  velocity_magnitude double precision DEFAULT 0,
  distance_traveled double precision DEFAULT 0,
  distance_from_last_marker double precision DEFAULT 0,
  nav_state text CHECK (nav_state = ANY (ARRAY['VISUAL_LOCK'::text, 'TRANSIT'::text, 'RED_ZONE'::text, 'INIT'::text, 'EMERGENCY'::text])),
  last_marker_id integer,
  current_zone text CHECK (current_zone = ANY (ARRAY['BLUE'::text, 'RED'::text, 'TRANSIT'::text])),
  position_confidence double precision DEFAULT 1.0,
  is_dead_reckoning boolean DEFAULT false,
  raw_sensor_data jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT mining_nav_positions_pkey PRIMARY KEY (id),
  CONSTRAINT mining_nav_positions_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.mining_nav_sessions(id)
);
CREATE TABLE public.mining_nav_sensor_readings (
  id bigint NOT NULL DEFAULT nextval('mining_nav_sensor_readings_id_seq'::regclass),
  session_id uuid,
  timestamp timestamp with time zone DEFAULT now(),
  accel_x double precision,
  accel_y double precision,
  accel_z double precision,
  gyro_x double precision,
  gyro_y double precision,
  gyro_z double precision,
  mag_x double precision,
  mag_y double precision,
  mag_z double precision,
  pitch_filtered double precision,
  roll_filtered double precision,
  yaw_filtered double precision,
  is_connected boolean DEFAULT true,
  data_quality double precision DEFAULT 1.0,
  CONSTRAINT mining_nav_sensor_readings_pkey PRIMARY KEY (id),
  CONSTRAINT mining_nav_sensor_readings_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.mining_nav_sessions(id)
);
CREATE TABLE public.mining_nav_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_name text NOT NULL,
  operator_name text,
  operator_id text,
  start_time timestamp with time zone DEFAULT now(),
  end_time timestamp with time zone,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'completed'::text, 'paused'::text, 'emergency'::text])),
  start_waypoint_id integer,
  current_zone text DEFAULT 'BLUE'::text CHECK (current_zone = ANY (ARRAY['BLUE'::text, 'RED'::text, 'TRANSIT'::text])),
  total_distance_m double precision DEFAULT 0,
  max_depth_m double precision DEFAULT 0,
  device_info jsonb DEFAULT '{}'::jsonb,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT mining_nav_sessions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.mining_nav_waypoints (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  marker_id integer NOT NULL UNIQUE,
  name text NOT NULL,
  description text,
  zone text DEFAULT 'BLUE'::text CHECK (zone = ANY (ARRAY['BLUE'::text, 'RED'::text, 'TRANSIT'::text])),
  abs_x double precision NOT NULL DEFAULT 0,
  abs_y double precision NOT NULL DEFAULT 0,
  abs_z double precision NOT NULL DEFAULT 0,
  is_active boolean DEFAULT true,
  marker_size_m double precision DEFAULT 0.10,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT mining_nav_waypoints_pkey PRIMARY KEY (id)
);
CREATE TABLE public.operator_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  operator_id text NOT NULL,
  operator_name text NOT NULL,
  operator_role text DEFAULT 'operator'::text,
  login_time timestamp with time zone NOT NULL DEFAULT now(),
  logout_time timestamp with time zone,
  session_duration_minutes integer,
  health_alerts_count integer DEFAULT 0,
  drill_alerts_count integer DEFAULT 0,
  device_info jsonb DEFAULT '{}'::jsonb,
  ip_address text,
  status text DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'completed'::text, 'abandoned'::text])),
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT operator_sessions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.operators (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  email text,
  shift_start timestamp with time zone,
  shift_end timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT operators_pkey PRIMARY KEY (id)
);
CREATE TABLE public.priest_bookings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  email character varying NOT NULL,
  phone character varying NOT NULL,
  puja_type character varying NOT NULL,
  preferred_date date NOT NULL,
  preferred_time time without time zone NOT NULL,
  address text,
  city character varying,
  state character varying,
  zip_code character varying,
  family_members text,
  gotra character varying,
  nakshatra character varying,
  special_requests text,
  status character varying DEFAULT 'pending'::character varying,
  priest_id uuid,
  admin_notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT priest_bookings_pkey PRIMARY KEY (id),
  CONSTRAINT priest_bookings_priest_id_fkey FOREIGN KEY (priest_id) REFERENCES public.priests(id)
);
CREATE TABLE public.priests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  email character varying,
  phone character varying,
  specialization character varying,
  experience_years integer,
  qualification character varying,
  address text,
  date_of_birth date,
  joining_date date DEFAULT CURRENT_DATE,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying]::text[])),
  notes text,
  image_url text,
  storage_path character varying,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT priests_pkey PRIMARY KEY (id)
);
CREATE TABLE public.puja_exceptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  series_id uuid NOT NULL,
  original_date date NOT NULL,
  action text NOT NULL,
  new_start timestamp with time zone,
  new_end timestamp with time zone,
  note text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT puja_exceptions_pkey PRIMARY KEY (id),
  CONSTRAINT puja_exceptions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.puja_instances (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  series_id uuid NOT NULL,
  starts_at timestamp with time zone NOT NULL,
  ends_at timestamp with time zone NOT NULL,
  status text DEFAULT 'active'::text,
  is_exception boolean DEFAULT false,
  original_date date,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT puja_instances_pkey PRIMARY KEY (id)
);
CREATE TABLE public.puja_participants (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  puja_id uuid,
  user_id uuid,
  registration_type text DEFAULT 'individual'::text CHECK (registration_type = ANY (ARRAY['individual'::text, 'family'::text, 'group'::text])),
  special_requests text,
  registered_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  attended boolean DEFAULT false,
  CONSTRAINT puja_participants_pkey PRIMARY KEY (id),
  CONSTRAINT puja_participants_puja_id_fkey FOREIGN KEY (puja_id) REFERENCES public.pujas(id),
  CONSTRAINT puja_participants_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.puja_series (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  type text DEFAULT 'puja'::text,
  location text,
  priest text,
  start_time text,
  duration_minutes integer DEFAULT 60,
  recurrence_type text DEFAULT 'none'::text,
  start_date date DEFAULT CURRENT_DATE,
  status text DEFAULT 'active'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  deity character varying,
  schedule_config jsonb DEFAULT '{}'::jsonb,
  notes text,
  CONSTRAINT puja_series_pkey PRIMARY KEY (id)
);
CREATE TABLE public.pujas (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  series_id uuid,
  scheduled_date date NOT NULL,
  scheduled_time time without time zone,
  actual_start_time timestamp with time zone,
  actual_end_time timestamp with time zone,
  status text DEFAULT 'scheduled'::text CHECK (status = ANY (ARRAY['scheduled'::text, 'in_progress'::text, 'completed'::text, 'cancelled'::text])),
  priest_id uuid,
  venue text,
  notes text,
  attendance_count integer DEFAULT 0,
  offerings jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT pujas_pkey PRIMARY KEY (id),
  CONSTRAINT pujas_priest_id_fkey FOREIGN KEY (priest_id) REFERENCES public.users(id)
);
CREATE TABLE public.reconciliation (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  donation_id uuid,
  expense_id uuid,
  date timestamp with time zone DEFAULT now(),
  status text DEFAULT 'unmatched'::text CHECK (status = ANY (ARRAY['matched'::text, 'unmatched'::text, 'exception'::text])),
  matched_with text,
  exception_reason text,
  reconciled_by uuid,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT reconciliation_pkey PRIMARY KEY (id)
);
CREATE TABLE public.shift_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  shift_id uuid NOT NULL,
  volunteer_id uuid NOT NULL,
  status text DEFAULT 'assigned'::text,
  assigned_at timestamp with time zone DEFAULT now(),
  assigned_by uuid,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT shift_assignments_pkey PRIMARY KEY (id)
);
CREATE TABLE public.system_settings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  key text NOT NULL UNIQUE,
  value jsonb NOT NULL,
  description text,
  is_system boolean DEFAULT false,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT system_settings_pkey PRIMARY KEY (id),
  CONSTRAINT system_settings_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.tasks (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  event_id uuid,
  community_id uuid,
  title text NOT NULL,
  description text,
  status text DEFAULT 'todo'::text CHECK (status = ANY (ARRAY['todo'::text, 'in_progress'::text, 'done'::text, 'cancelled'::text])),
  priority text DEFAULT 'medium'::text CHECK (priority = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text])),
  assignee_id uuid,
  due_date timestamp with time zone,
  completed_at timestamp with time zone,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT tasks_pkey PRIMARY KEY (id),
  CONSTRAINT tasks_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id),
  CONSTRAINT tasks_community_id_fkey FOREIGN KEY (community_id) REFERENCES public.communities(id),
  CONSTRAINT tasks_assignee_id_fkey FOREIGN KEY (assignee_id) REFERENCES public.users(id),
  CONSTRAINT tasks_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.timeline (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  event_type text NOT NULL,
  entity text NOT NULL,
  entity_id uuid NOT NULL,
  details jsonb,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT timeline_pkey PRIMARY KEY (id),
  CONSTRAINT timeline_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id)
);
CREATE TABLE public.tracking_alerts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  device_id uuid,
  type text NOT NULL CHECK (type = ANY (ARRAY['emergency'::text, 'breakdown'::text, 'geofence_enter'::text, 'geofence_exit'::text, 'low_battery'::text, 'signal_lost'::text, 'speeding'::text, 'offline'::text])),
  priority text DEFAULT 'medium'::text CHECK (priority = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'critical'::text])),
  message text NOT NULL,
  latitude double precision,
  longitude double precision,
  depth double precision,
  zone text,
  is_read boolean DEFAULT false,
  is_resolved boolean DEFAULT false,
  resolved_at timestamp with time zone,
  resolved_by text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT tracking_alerts_pkey PRIMARY KEY (id),
  CONSTRAINT tracking_alerts_device_id_fkey FOREIGN KEY (device_id) REFERENCES public.tracking_devices(id)
);
CREATE TABLE public.tracking_devices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  device_id text NOT NULL UNIQUE,
  name text NOT NULL,
  type text NOT NULL DEFAULT 'mining_vehicle'::text CHECK (type = ANY (ARRAY['mining_vehicle'::text, 'personnel'::text, 'equipment'::text, 'drill'::text])),
  status text DEFAULT 'operational'::text CHECK (status = ANY (ARRAY['operational'::text, 'breakdown'::text, 'maintenance'::text, 'emergency'::text, 'offline'::text])),
  battery_level integer DEFAULT 100 CHECK (battery_level >= 0 AND battery_level <= 100),
  is_online boolean DEFAULT false,
  last_seen_at timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT tracking_devices_pkey PRIMARY KEY (id)
);
CREATE TABLE public.tracking_positions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  device_id uuid,
  latitude double precision NOT NULL,
  longitude double precision NOT NULL,
  depth double precision DEFAULT 0,
  altitude double precision DEFAULT 0,
  speed double precision DEFAULT 0,
  heading double precision DEFAULT 0,
  accuracy double precision DEFAULT 0,
  signal_strength integer DEFAULT 100 CHECK (signal_strength >= 0 AND signal_strength <= 100),
  zone text,
  timestamp timestamp with time zone DEFAULT now(),
  raw_data jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT tracking_positions_pkey PRIMARY KEY (id),
  CONSTRAINT tracking_positions_device_id_fkey FOREIGN KEY (device_id) REFERENCES public.tracking_devices(id)
);
CREATE TABLE public.tracking_zones (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['safe'::text, 'restricted'::text, 'hazard'::text, 'emergency_point'::text, 'tunnel'::text, 'shaft'::text, 'extraction'::text])),
  level integer DEFAULT 0,
  center_lat double precision NOT NULL,
  center_lng double precision NOT NULL,
  radius double precision DEFAULT 100,
  depth_min double precision DEFAULT 0,
  depth_max double precision DEFAULT 0,
  alert_on_enter boolean DEFAULT false,
  alert_on_exit boolean DEFAULT false,
  is_active boolean DEFAULT true,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT tracking_zones_pkey PRIMARY KEY (id)
);
CREATE TABLE public.transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  category_id uuid,
  type text NOT NULL CHECK (type = ANY (ARRAY['income'::text, 'expense'::text])),
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  description text NOT NULL,
  date date DEFAULT CURRENT_DATE,
  payment_method text DEFAULT 'cash'::text CHECK (payment_method = ANY (ARRAY['cash'::text, 'card'::text, 'bank_transfer'::text, 'upi'::text, 'cheque'::text])),
  reference_number text,
  status text DEFAULT 'completed'::text CHECK (status = ANY (ARRAY['pending'::text, 'completed'::text, 'cancelled'::text])),
  notes text,
  created_by text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT transactions_pkey PRIMARY KEY (id),
  CONSTRAINT transactions_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.budget_categories(id)
);
CREATE TABLE public.user_roles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  role text NOT NULL,
  community_id uuid,
  granted_by uuid,
  granted_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone,
  is_active boolean DEFAULT true,
  CONSTRAINT user_roles_pkey PRIMARY KEY (id),
  CONSTRAINT user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_roles_granted_by_fkey FOREIGN KEY (granted_by) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL,
  email text NOT NULL UNIQUE,
  full_name text NOT NULL,
  status USER-DEFINED DEFAULT 'pending'::user_status,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  phone text,
  avatar_url text,
  metadata jsonb DEFAULT '{}'::jsonb,
  preferences jsonb DEFAULT '{"notifications": {"push": true, "email": true, "whatsapp": true}}'::jsonb,
  last_login_at timestamp with time zone,
  deleted_at timestamp with time zone,
  password_hash text,
  date_of_birth date,
  gender text CHECK (gender = ANY (ARRAY['male'::text, 'female'::text, 'other'::text])),
  address jsonb,
  emergency_contact jsonb,
  role text DEFAULT 'user'::text,
  auth_provider text DEFAULT 'local'::text,
  email_verified boolean DEFAULT false,
  phone_verified boolean DEFAULT false,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.volunteer_applications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  community_id uuid,
  user_id uuid,
  first_name character varying NOT NULL,
  last_name character varying,
  email character varying NOT NULL,
  phone character varying,
  skills ARRAY DEFAULT '{}'::text[],
  interests ARRAY DEFAULT '{}'::text[],
  motivation text,
  experience text,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'approved'::character varying, 'rejected'::character varying, 'withdrawn'::character varying]::text[])),
  applied_at timestamp with time zone DEFAULT now(),
  reviewed_at timestamp with time zone,
  reviewed_by uuid,
  review_notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT volunteer_applications_pkey PRIMARY KEY (id),
  CONSTRAINT volunteer_applications_community_id_fkey FOREIGN KEY (community_id) REFERENCES public.communities(id)
);
CREATE TABLE public.volunteer_assignments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  shift_id uuid,
  volunteer_id uuid,
  status text DEFAULT 'assigned'::text CHECK (status = ANY (ARRAY['assigned'::text, 'confirmed'::text, 'completed'::text, 'cancelled'::text])),
  assigned_by uuid,
  assigned_at timestamp with time zone DEFAULT timezone('utc'::text, now()),
  completed_at timestamp with time zone,
  notes text,
  rating numeric CHECK (rating >= 0::numeric AND rating <= 5::numeric),
  feedback text,
  CONSTRAINT volunteer_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT volunteer_assignments_volunteer_id_fkey FOREIGN KEY (volunteer_id) REFERENCES public.users(id),
  CONSTRAINT volunteer_assignments_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES public.users(id)
);
CREATE TABLE public.volunteer_attendance (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  volunteer_id uuid,
  shift_id uuid,
  status character varying DEFAULT 'scheduled'::character varying CHECK (status::text = ANY (ARRAY['scheduled'::character varying, 'pending'::character varying, 'present'::character varying, 'absent'::character varying, 'late'::character varying, 'completed'::character varying, 'excused'::character varying]::text[])),
  check_in_time timestamp with time zone,
  check_out_time timestamp with time zone,
  hours_worked numeric,
  notes text,
  attendance_date date,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT volunteer_attendance_pkey PRIMARY KEY (id),
  CONSTRAINT volunteer_attendance_volunteer_id_fkey FOREIGN KEY (volunteer_id) REFERENCES public.volunteers(id),
  CONSTRAINT volunteer_attendance_shift_id_fkey FOREIGN KEY (shift_id) REFERENCES public.volunteer_shifts(id)
);
CREATE TABLE public.volunteer_profiles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid UNIQUE,
  skills ARRAY,
  interests ARRAY,
  availability jsonb,
  emergency_contact jsonb,
  background_check_status text DEFAULT 'pending'::text CHECK (background_check_status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text])),
  onboarding_completed boolean DEFAULT false,
  total_hours_volunteered integer DEFAULT 0,
  rating numeric CHECK (rating >= 0::numeric AND rating <= 5::numeric),
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT volunteer_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT volunteer_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.volunteer_shifts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  community_id uuid,
  title character varying NOT NULL,
  description text,
  location character varying,
  shift_date date NOT NULL,
  start_time time without time zone NOT NULL,
  end_time time without time zone NOT NULL,
  required_volunteers integer DEFAULT 1,
  skills_required ARRAY DEFAULT '{}'::text[],
  status character varying DEFAULT 'open'::character varying CHECK (status::text = ANY (ARRAY['open'::character varying, 'filled'::character varying, 'completed'::character varying, 'cancelled'::character varying]::text[])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT volunteer_shifts_pkey PRIMARY KEY (id),
  CONSTRAINT volunteer_shifts_community_id_fkey FOREIGN KEY (community_id) REFERENCES public.communities(id)
);
CREATE TABLE public.volunteers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  community_id uuid,
  first_name character varying NOT NULL,
  last_name character varying NOT NULL,
  email character varying NOT NULL,
  phone character varying,
  date_of_birth date,
  address jsonb DEFAULT '{}'::jsonb,
  emergency_contact jsonb DEFAULT '{}'::jsonb,
  skills ARRAY DEFAULT '{}'::text[],
  interests ARRAY DEFAULT '{}'::text[],
  availability jsonb DEFAULT '{}'::jsonb,
  notes text,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying, 'pending'::character varying, 'suspended'::character varying]::text[])),
  total_hours_volunteered numeric DEFAULT 0,
  rating numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT volunteers_pkey PRIMARY KEY (id),
  CONSTRAINT volunteers_community_id_fkey FOREIGN KEY (community_id) REFERENCES public.communities(id)
);